sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script:
- docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar make spiralbook

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Smacc
  skip_cleanup: true
  user: cdlm
  key:
    secure: yGqRzDgQ6Zr7WMTyeEezUhssm6Yo0duymtZ9MekMBsjK8t51ad+ylP3oRL7COwuhrcVhfP7shis+Ltp8+qQigQXMSh+uhKx9n1vCke0DEvwWuORNbqxGSHAi6xdR/IbonXC+a3rk1D6HtjtsXz1v+zLSq0dK6TiSPUof0MHyY+VbICULH0Wiok/Ly9M9Uw6GHIXZ5p4W0nvUau14ASGoaqNLJ7XQOBP7yXHndKbTwbysp4v6cvODUjxQBzze21dN5Tg/POWciA8cI7RyD9ZM6uqhCeZNsUWiIuEMX15dRPQB5DMuEF1yxDn/IF6FMbMbsguSnXcomPsp7LmJY6WW8O9nXzSWs5tMnInDsN/Y2kAhIUwBLvO1/fwsrqH6fnx5aK0VrqAD8+vaksSphZuoIYPF9vVXRrciQRaqR5Wfay2PCEcHQZTb9JS65mOnhv4ovuCScbksp2AEG5EVuqBiGzpNaNZ41EALzUU9Uh6UgN32jqQ2WFFNKzdFRdxQnSz7/99zpXWl9nGQhRUFFyLewRtZGS1DzQ2NMqvkImMVAo/Hs8mZ1Xrxwz5eneHmZfoOATjiXPbuiLpM2hg+NIOZvURrefitW6w6xOoJfPZFIlyPxHYUJuy39aSCdpaAHreB3iqCs3FmsHhdIC36oStOBjtYyklKiQ2J9VxqXVXIKZI=
- provider: releases
  file: build/smacc.spiral.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
